#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NotificationChannels.Resource", IsApplication=true)]

namespace NotificationChannels
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int tile = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int activity_main = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int btnA = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int main_footer = 2131296265;
			
			// aapt resource value: 0x7f090004
			public const int main_primary_config = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int main_primary_send1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int main_primary_send2 = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int main_primary_title = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int main_secondary_config = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int main_secondary_send1 = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int main_secondary_send2 = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int main_secondary_title = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int btn1_description = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btn1_title = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int btnA_title = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int main_create_noti2_btn = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int main_primary_config = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int main_primary_send1 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int main_primary_send2 = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int main_primary_title = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int main_secondary_config = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int main_secondary_send1 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int main_secondary_send2 = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int main_secondary_title = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int noti1_title = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int noti2_title = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int noti_channel_default = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int noti_channel_second = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int primary1_body = 2131165194;
			
			// aapt resource value: 0x7f070016
			public const int primary2_body = 2131165206;
			
			// aapt resource value: 0x7f07000c
			public const int secondary1_body = 2131165196;
			
			// aapt resource value: 0x7f070017
			public const int secondary2_body = 2131165207;
			
			// aapt resource value: 0x7f070005
			public const int simple_service_desc = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int simple_service_title = 2131165188;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_AppTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Widget = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Widget_SampleMessage = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int Widget_SampleMessageTile = 2131230723;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
